### ISSUE TITLE
[Incompatability] Extensive screen jitter in front-facing third-person

### ISSUE THREAD

**Issue by IdrisQe** [Mirsario/Minecraft-CameraOverhaul#11] opened 2021-02-20 00:44 UTC
With ImmersivePortals Fabric installed, even if no portals are present in the world, going into the second third-person mode where the camera is pointed at your face, the screen will rapidly tilt left and right continuously what seems like every frame, even when you're standing still, but only in this mode. Behind-head third person and first person continue to work fine.

Confirmed the bug with only CameraOverhaul and ImmersivePortals Fabric
Minecraft 1.16.5; Fabric 0.11.1; Fabric API 0.30.3; CameraOverhaul 1.2.2; ImmersivePortals Fabric 0.68
https://github.com/qouteall/ImmersivePortalsMod/issues/587

This also occurs with the unofficial CameraOverhaul Forge port and ImmersivePortals Forge

**Comment by MopsTMC** [comment] 2021-02-21 18:17
I can confirm this, found out about this issue earlier today. This seems to be an incompatibility with multiple mods and not just ImmersivePortals as seen in #12.

**Comment by ZSvengali** [comment] 2021-02-26 17:35
I've also been receiving excessive camerashaking as well in front facing third person with Forge.

**Comment by Mysticpasta1** [comment] 2021-05-10 01:02
this still happens with recent versions of everything.

**Comment by Mirsario** [comment] 2024-12-20 16:46
Should be fixed in 2.0, which will be released soon-ish.
Pre-release builds in case anyone wants to test them: [CameraOverhaul-2024-12-20.zip](https://github.com/user-attachments/files/18213163/CameraOverhaul-2024-12-20.zip)

**Closed as completed by Mirsario** 2024-12-20 16:46 UTC
